var bridge = window['VxBridge'];
module.exports = {
'create':bridge.create,
'getRenderer':bridge.getRenderer,
'getRendererType':bridge.getRendererType,
'getDomElement':bridge.getDomElement,
'resetClass':bridge.resetClass,
'addClass':bridge.addClass,
'addWidget':bridge.addWidget,
'removeWidget':bridge.removeWidget,
'setLinks':bridge.setLinks,
'render':bridge.render,
'createGraphics':bridge.createGraphics,
'encryptData':bridge.encryptData,
'encryptData':bridge.encryptData,
'decryptData':bridge.decryptData,
'createSelector':bridge.createSelector,
'selectWidget':bridge.selectWidget,
'updateSelector':bridge.updateSelector,
'addMouseDownHandler':bridge.addMouseDownHandler,
'isDom':bridge.isDom,
'setGenerateText':bridge.setGenerateText,
'isTimer':bridge.isTimer,
'timerAddCallback':bridge.timerAddCallback,
'timerRemoveCallback':bridge.timerRemoveCallback,
};
